query deployments($where: DeploymentsWhereInput!, $filter: DeploymentsPaginationInput) {
  deployments(where: $where, filter: $filter) {
    pageCount
    data {
      cid
      id
      status
      createdAt
      startedAt
      sourceProvider
      sourceAuthor
      sourceMessage
      sourceRepositoryName
      sourceRepositoryOwner
      previewImageUrl
      previewOnly
      storageType
      sourceBranch
      updatedAt
      sourceRef
      previewUrlSlug
    }
    totalCount
  }
}
