query ensRecordsByIpnsId(
  $where: EnsRecordsByIpnsIdWhereInput!
  $filter: EnsRecordsByIpnsIdPaginationInput
) {
  ensRecordsByIpnsId(where: $where, filter: $filter) {
    data {
      id
      name
      createdAt
      status
    }
  }
}
