query projectMembers($where: ProjectWhereInput!) {
  project(where: $where) {
    id
    memberships {
      id
      role
      createdAt
      permissionGroup {
        id
        name
        description
      }
      user {
        id
        email
        username
      }
    }
  }
}
