import { amber, amberDark, gray, grayDark, green, greenDark, red, redDark, yellow, yellowDark } from '@radix-ui/colors';

export const surface = {
  light: {
    'surface-primary': '$white',
    'surface-secondary': gray.gray2,
    'surface-tertiary': gray.gray3,
    'surface-actionable': gray.gray4,
    'surface-monochrome': '$white',
    'surface-content-fill': '$white',

    'surface-amber-actionable': amber.amber4,
    'surface-amber-light': amber.amber3,
    'surface-amber-lighter': amber.amber1,
    'surface-red-actionable': red.red4,
    'surface-red-light': red.red3,
    'surface-red-lighter': red.red1,
    'surface-yellow-actionable': yellow.yellow4,
    'surface-yellow-light': yellow.yellow3,
    'surface-yellow-lighter': yellow.yellow1,
    'surface-green-actionable': green.green4,
    'surface-green-light': green.green3,
    'surface-green-lighter': green.green1,
    'surface-logo': '$black',
    'surface-app-background': gray.gray2,
    'surface-avatar-icon': gray.gray5,
    'surface-filecoin': '#4690FF',
    'surface-ipfs': '#E3FDFF',
    'surface-ens': '#F3F3FF',
    'surface-skeleton': gray.gray6,
  },
  dark: {
    'surface-primary': grayDark.gray1,
    'surface-secondary': grayDark.gray2,
    'surface-tertiary': grayDark.gray3,
    'surface-actionable': grayDark.gray4,
    'surface-monochrome': '$black',
    'surface-content-fill': grayDark.gray2,

    'surface-amber-actionable': amberDark.amber4,
    'surface-amber-light': amberDark.amber3,
    'surface-amber-lighter': amberDark.amber1,
    'surface-yellow-actionable': yellowDark.yellow4,
    'surface-yellow-light': yellowDark.yellow3,
    'surface-yellow-lighter': yellowDark.yellow1,
    'surface-red-actionable': redDark.red4,
    'surface-red-light': redDark.red3,
    'surface-red-lighter': redDark.red1,
    'surface-green-actionable': greenDark.green4,
    'surface-green-light': greenDark.green3,
    'surface-green-lighter': greenDark.green1,
    'surface-logo': '$white',
    'surface-app-background': '$black',
    'surface-avatar-icon': grayDark.gray5,
    'surface-filecoin': '#4690FF',
    'surface-ipfs': '#E3FDFF',
    'surface-ens': '#F3F3FF',
    'surface-skeleton': grayDark.gray6,
  },
};
