query migrationTeamInfosFromToken(
  $where: MigrationTeamInfosFromTokenWhereInput!
) {
  migrationTeamInfosFromToken(where: $where) {
    id
    name
    filesCount
    sitesCount
    usersCount
  }
}
