query gitRepositories($where: GitApiInstallationsWhereInput!) {
  gitApiInstallations(where: $where) {
    avatar
    installationId
    isOrganization
    name
    repos {
      id
      defaultBranch
      name
    }
  }
}
