#!/bin/bash

if [[ -z "$1" ]]; then
  echo "👹 Oops! Missing port number."
  exit 1
fi

max_count=10
count=0
timeout=15
dev_server_url="http://localhost:$1"
http_success_status="HTTP/1.1 200 OK"


echo "🤖 Await for development server at $dev_server_url"

while ! curl -sfLI "$dev_server_url" | grep -q "$http_success_status"; do
  if [[ $count -ge $max_count ]]; then
    echo "👹 Oops! The dev server failed to start after $max_count for some reason..."
    exit 1
  fi
    
  echo "⏳ Waiting for dev server..."

  count=$((count + 1))
  sleep "$timeout"
done

echo "✅ Dev server is ready!"
