#!/bin/bash

# Required vars (shared)
source .scripts/test_runner_vars

outputDir="out"
outputBakDir="$outputDir.bak"
indexForRedirectBaseDir="$outputDir/index.html"

echo "👷 Build Static site..."

echo "🤖 Run next build..."

if ! pnpm exec next build; then
  echo "👹 Oops! Nextjs build failed"
  exit 1
fi

echo "🤖 Generate sitemap..."
if ! pnpm run generate:sitemap; then
  echo "👹 Oops! Sitemap generator failure"
  exit 1
fi

echo "🤖 Copy public assets to $build_out_path"
if ! cp -r public/* "$build_out_path"; then
  echo "👹Oops! Failed to copy public assets to distribution directory"
  exit 1
fi

.scripts/test_run_hash_signature > "$build_hash_path"

echo
echo "👍 Static site builder completed!"
