#!/bin/bash

dist_path="out"
build_hash="$dist_path/hash"

echo "👷 Build Static site..."

echo "🤖 Run next build..."
if ! next build; then
  echo "👹 Oops! Nextjs build failed"
  exit 1
fi

echo "🤖 Generate sitemap..."
if ! pnpm run generate:sitemap; then
  echo "👹 Oops! Sitemap generator failure"
  exit 1
fi

echo "🤖 Copy public assets to $dist_path"
if ! cp -r public/* "$dist_path"; then
  echo "👹Oops! Failed to copy public assets to distribution directory"
  exit 1
fi

.scripts/test_run_hash_signature > "$build_hash"

echo
echo "👍 Static site builder completed!"
