#!/bin/bash

format() {
  echo "$1" | cut -d ' ' -f2
}

# Required vars (shared)
source .scripts/test_runner_vars

tests_path="./tests"
expected=$(cat "$info_path")
hash=$(.scripts/hash_dir "$csv_paths")
current="[TEST_RUN] $hash"

echo "🔍 Check for local test run..."

if [[ "$current" != "$expected" ]]; then
	echo "⚠️Expected $(format "$expected"), but got $(format "$current")"
	exit 1
fi

echo "✅ Test runs match expected $hash"

exit 0
