#!/bin/bash

format() {
  echo "$1" | cut -d ' ' -f2
}

# Required vars (shared)
source .scripts/test_runner_vars

expected=$(cat "$info_path")
current_has_signature=$(.scripts/test_run_hash_signature)
hash=$(echo "$current_has_signature" | cut -d ' ' -f2)
hash_trimmed="${hash:0:6}"

echo "🔍 Check for local test run with $hash_trimmed..."

if [[ "$current_has_signature" != "$expected" ]]; then
	echo "⚠️Expected $(format "$expected"), but got $(format "$current_has_signature")"
	exit 1
fi

echo "✅ Test runs match expected $hash"

exit 0
