#!/bin/bash

if [[ -z "$1" ]]; then
  echo "👹 Oops! Missing source argument. Call the script with an argument for directory path, e.g. hash_dir ./src"
  exit 1
fi

args=($(echo "$1" | sed 's/,/ /g' | xargs))

# This command finds all files in the directory,
# sorts them alphabetically, hashes their contents 
# to generate individual file hashes, then creates 
# a shorter overall hash of those individual hashes
find "${args[@]}" -type f | sort | xargs shasum | shasum | cut -d ' ' -f1
