#!/bin/bash

if [[ -z "$1" ]]; then
  echo "👹 Oops! Missing source argument. Call the script with an argument for directory path, e.g. hash_dir ./src"
  exit 1
fi


if [[ "$OSTYPE" == "darwin"* ]]; then
  find $1 -type f -exec md5 {} \; | sort | md5
else
  find $1 -type f -exec md5sum {} \; | sort | md5sum
fi
