#!/bin/bash

# Required dotenv utils
source .scripts/dotenv_utils

# Variables setup
dev_environment="development"
dot_env_ls=$(getDotEnvs)
dot_env_count=$(getDotEnvs | wc -w | xargs)
check_env_filename=""
test_artifacts_path=".tests"

dotEnvUserInputHandling \
  "$dev_environment" \
  "$dot_env_count" \
  "$dot_env_ls" \
  "$dot_env_count" \
  "$check_env_filename" \
  "$test_artifacts_path"

# Requirements quick check
pnpm dev:check_required

# The test server is interested
# in the port number
createTestsDotEnv \
  "$test_artifacts_path" \
  "$tests_dot_env_path"

echo "🤖 Should start the React Scan server at localhost:$NEXT_DEV_SERVER_PORT..."

pnpm exec react-scan "localhost:$NEXT_DEV_SERVER_PORT"
