#!/bin/bash

echo "👷 Put build in base path (if required)..."

if [[ -z "$NEXT_PUBLIC_DASHBOARD_BASE_PATH" && -z "$CI" ]]; then
  echo "🦖 Skipping build static files due to be running outside CI. The dev server should suggest the address with base path for you!"

  exit 0
fi

if [[ -n "$NEXT_PUBLIC_DASHBOARD_BASE_PATH" && "$NEXT_PUBLIC_DASHBOARD_BASE_PATH" != '/' ]]; then
  echo "🤖 Must copy files to base path $NEXT_PUBLIC_DASHBOARD_BASE_PATH..."
  
  mv "$outputDir" "$outputBakDir"
  mkdir -p "$outputWithBaseDir"

  if ! cp -r "$outputBakDir"/* "$outputWithBaseDir"; then
    echo "👹 Oops! Failed to copy $outputDir to $outputWithBaseDir for some reason..."
    exit 1
  else
    echo "✅ Copied output files to $outputWithBaseDir"
  fi

  echo "<html><head><script>window.location.href=\"$NEXT_PUBLIC_DASHBOARD_BASE_PATH\";</script></head></html>" > "$indexForRedirectBaseDir"
fi

echo
echo "👍 Put build in base path completed!"
