#!/bin/bash

echo "👷 Put build in base path (if required)..."

if [[ -z "$NEXT_PUBLIC_DASHBOARD_BASE_PATH" && -z "$CI" ]]; then
  echo "🦖 Skipping build static files due to be running outside CI. The dev server should suggest the address with base path for you!"

  exit 0
fi

outputDir="out"
outputBakDir="$outputDir.bak"
outputWithBaseDir="$outputDir/$NEXT_PUBLIC_DASHBOARD_BASE_PATH"
agentsDir="$outputDir/$NEXT_PUBLIC_AGENTS_AI_PATH"
indexForRedirectBaseDir="$outputDir/index.html"
indexForAgentsBasePath="$agentsDir/index.html"
indexForMainApp="$outputDir/$NEXT_PUBLIC_DASHBOARD_BASE_PATH/index.html"
redirectsFilepath="public/_redirects"

if [[ -n "$NEXT_PUBLIC_DASHBOARD_BASE_PATH" && "$NEXT_PUBLIC_DASHBOARD_BASE_PATH" != '/' ]]; then
  echo "🤖 Must copy files to base path $NEXT_PUBLIC_DASHBOARD_BASE_PATH..."
  
  mv "$outputDir" "$outputBakDir"
  mkdir -p "$outputWithBaseDir"

  if ! cp -r "$outputBakDir"/* "$outputWithBaseDir"; then
    echo "👹 Oops! Failed to copy $outputDir to $outputWithBaseDir for some reason..."
    exit 1
  else
    echo "✅ Copied output files to $outputWithBaseDir"
  fi

  echo "🤖 Copy redirects file to root"
  cp "$redirectsFilepath" "$outputDir"

  echo "<html><head><script>window.location.href=\"$NEXT_PUBLIC_DASHBOARD_BASE_PATH\";</script></head></html>" > "$indexForRedirectBaseDir"

  mkdir -p "$agentsDir"

  echo "<html><body><h1>Repository environment only</h1><p>This is a repository environment. Visit the website environment instead to cross link to Agents, e.g. here's <a href=\"https://fleek-xys-staging.fleeksandbox.xyz/$NEXT_PUBLIC_DASHBOARD_BASE_PATH\">fleek-xyz-staging</a> or alternative visit the agents repository environment <a href=\"https://fleek-agents-staging.fleeksandbox.xyz/$NEXT_PUBLIC_AGENTS_AI_PATH\">fleek-agents-staging</a></p></body></html>" > "$indexForAgentsBasePath"
fi

echo
echo "👍 Put build in base path completed!"
