#!/bin/bash

showErrorMsg() {
  echo "👹 Oops! Required port $port is in use. Close the process using port $port and try again!"
}

ui_ports=(3000 3001 3002)
ui_port_count=0
storybook_port=6006

for port in "${ui_ports[@]}"; do
  if ! lsof -i :$port | grep -q LISTEN; then
    ((ui_port_count+=1))
    echo "🔎 Port $port is free"
  fi
done

if [[ "$ui_port_count" -eq 0 ]]; then
  showErrorMsg
  exit 1
fi

if lsof -i :$storybook_port | grep -q LISTEN; then
  showErrorMsg
  exit 1
else
  echo "🔎 Port $storybook_port is free"
fi
    
echo "✅ Required dev ports are free!"
