#!/bin/bash

# Should wait for development server readyness
.scripts/await_dev_server "$NEXT_DEV_SERVER_PORT"

onFailure() {
  echo "👹 Oops! Test runner failed!"
  exit 1
}

trap cleanup SIGINT

echo "🤖 Should start the e2e tests..."
if ! pnpm run test:e2e; then
  onFailure
fi

echo "🤖 Should start the unit tests..."
if ! pnpm run test:unit; then
  onFailure
fi

# Required vars (shared)
source .scripts/test_runner_vars

hash=$(.scripts/hash_dir "$csv_paths")

if [[ -z "$hash" ]]; then
  echo "👹 Oops! Failed to hash source directory for test runner"
  exit 1
fi

echo "[TEST_RUN] $hash" > "$info_path"

echo
echo "✅ Test runner completed!"
