#!/bin/bash

targetEnvPath=".env"
# Using dotenv due to `fleek sites deploy`
# failing to authenticate via the host or declared
# fleek env vars for some reason
doppler secrets download \
  --no-file \
  --format env > "$targetEnvPath"

if [[ ! -z "$NEXT_PUBLIC_ALLOW_LANDING_PAGE_LOGIN" ]]; then
  echo "NEXT_PUBLIC_ALLOW_LANDING_PAGE_LOGIN=\"$NEXT_PUBLIC_ALLOW_LANDING_PAGE_LOGIN\"" >> "$targetEnvPath"
fi

# The Fleek CLI supports envVars overrides
# also other cases such as the website url
# for this reason, we should exclude some vars
# originated from doppler
EXCLUDE_CSV=( "UI__APP_URL" "SDK__GRAPHQL_API_URL" "SDK__AUTH_APPS_URL" "SDK__IPFS__STORAGE_API_URL" "SDK__UPLOAD_PROXY_API_URL" "SITE_SLUG_DOMAIN" "NEXT_PUBLIC_WEBSITE_URL" )

for item in "${EXCLUDE_CSV[@]}"; do
  if [[ "$OSTYPE" == "darwin"* ]]; then
    sed -i '' "/^${item}=/d" "$targetEnvPath"
  else
    sed -i "/^${item}=/d" "$targetEnvPath"
  fi
done

for item in "${EXCLUDE_CSV[@]}"; do
  if grep -q "^${item}=" "$targetEnvPath"; then
    echo "👹 Oops! Failed to exclude $item from $targetEnvPath"
    exit 1
  fi
done

echo "✅ Completed dot env setup!"
