#!/bin/bash

set -e

# Required dotenv utils
source .scripts/dotenv_utils

startDevServer() {
  echo "🤖 Should start the server at localhost:$NEXT_DEV_SERVER_PORT..."
  pnpm exec next dev --port $NEXT_DEV_SERVER_PORT
}

# Interactive mode setup
interactive_mode=$([[ -n "$CI" ]] && { [[ "$CI" = "true" ]] || [[ "$CI" = "1" ]]; } && echo 0 || echo 1)

# Variables setup
dev_environment="development"
dot_env_ls=$(getDotEnvs)
dot_env_count=$(getDotEnvs | wc -w | xargs)
check_env_filename=""
test_artifacts_path=".tests"

if [[ "$interactive_mode" -eq 1 ]]; then
  dotEnvUserInputHandling \
    "$dev_environment" \
    "$dot_env_count" \
    "$dot_env_ls" \
    "$dot_env_count" \
    "$check_env_filename" \
    "$test_artifacts_path"

  # Requirements quick check
  pnpm dev:check_required
fi

# The test server is interested
# in the port number
createTestsDotEnv \
  "$test_artifacts_path" \
  "$tests_dot_env_path"

echo "🤖 Should start the server at localhost:$NEXT_DEV_SERVER_PORT..."
pnpm exec next dev --port $NEXT_DEV_SERVER_PORT
