#!/bin/bash

# Required environment vars
source ".tests/.env"

PORT="$UI_TEST_HTTP_SERVER_PORT"
SERVER_NAME="http-server"

echo "🔫 Attempting to terminate $SERVER_NAME on port $PORT..."

# Try SIGTERM first
if lsof -t -i "tcp:$PORT" | xargs -r kill -15 >/dev/null 2>&1; then
    echo "🤖Wait a moment for graceful shutdown..."
    sleep 1
fi

if ! lsof -t -i "tcp:$PORT" | xargs -r kill -9 >/dev/null 2>&1; then
    echo "👹 Oops! Unable to terminate $SERVER_NAME on port $PORT"
    exit 1
fi

echo "✅ Terminated $SERVER_NAME on port $PORT"
