export const sizes = {
  max: 'max-content',
  min: 'min-content',
  full: '100%',
  '5xs': '6rem',
  '4xs': '10rem',
  '3xs': '14rem',
  '2xs': '16rem',
  xs: '20rem',
  sm: '24rem',
  md: '28rem',
  lg: '32rem',
  xl: '36rem',
  '2xl': '42rem',
  '3xl': '48rem',
  '4xl': '56rem',
  '5xl': '64rem',
  '6xl': '72rem',
  '7xl': '80rem',
  '8xl': '90rem',

  'page-content': '75rem',
  'header-height': '3.8125rem',
  'sidebar-width': '40vw',
  'small-divider-height': '0.08rem',
  'min-empty-height': '40vh',
  'min-empty-height-table': '33rem',
  'min-page-height': '100vh',
  'min-content-height': 'calc(100vh - $header-height)',
  'modal-width': '26.5rem',

  'inline-component-height-xs': '0.5em',
  'inline-component-height-sm': '0.75em',
  'inline-component-height-md': '1em',
  'inline-component-height-lg': '2em',
  'inline-component-height-xl': '3em',
};
