name: ⚡️ Deploy Site

on:
  workflow_dispatch:
  push:

jobs:
  deploy-to-staging:
    uses: ./.github/workflows/fleek-deploy-common.yml
    with:
      environment: staging
    secrets: inherit

  deploy-to-production:
    uses: ./.github/workflows/fleek-deploy-common.yml
    with:
      environment: production
    secrets: inherit
